---
helm_charts: 
  - 
    name: "bitnami"
    url: "https://charts.bitnami.com/bitnami"


namespaces: ["desarrollo", "produccion"]
prod_apps:
 - 
  name: nginx-server
  chart_name: bitnami/nginx

dev_apps:
 - 
  name: nginx-server
  chart_name: bitnami/nginx

